### ISSUE TITLE
Lägga till mail/telefon/twitter info till medarbetarna?

### ISSUE THREAD

**Issue by AndersLowenborg** [aptitud/aptitud.github.io#1]

**Comment by perjansson** [comment]
Klart!

Om nån hittar en bättre Bootstrap Glyphicon än en jordglob till Twitterlänken så byt gärna. Annars uppdatera fellows.js för att lägga till info.

![skarmavbild 2015-02-16 kl 21 44 51](https://cloud.githubusercontent.com/assets/1557938/6219034/1c2c0ae6-b625-11e4-92f4-049c4d1bd9de.png)

**Comment by marcusoftnet** [comment]
Tja, 

fixade detta och gick över till ikoner istället. Tar mindre plats. Använder dessutom font-awesome's ikoner som ger möjligheter till en hel massa fler saker för den som vill; LinkedIn, Facebook or what have you. http://fortawesome.github.io/Font-Awesome/icons/

lade dessutom till GitHub som kändes naturligt för oss (har med mig själv som exempel). 

https://github.com/aptitud/AptiWeb2.0/commit/047f993a21e856f0fa4fb48a3de2825e02cdfd12
