### ISSUE TITLE
Undvik spam genom att bygga epost-adress onClick

### ISSUE THREAD

**Issue by perjansson** [aptitud/aptitud.github.io#5]
För att undvika massa spam (vår email står i klartext i maillänken) så kan vi istället onClick bygga e-postadressen. T ex: förnamn + punkt + efternamn, ersätt svenska tecken, gör till lower case + @aptitud.se.

**Comment by marcusoftnet** [comment]
Jag kan kolla på den. När jag får nätet tillbaka

**Comment by marcusoftnet** [comment]
Så det betyder att man nu kan ta bort sin email address från fellow.json. 

Ditt namn skriver sitt namn så att det blir korrekt email då man:
- Ersätter mellanslag med en punkt
- Ersätter å och ä med a och ö med o
